# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\CLion 2025.1.2\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "D:\CLion 2025.1.2\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\user\CLionProjects\ollaborative-filtering-system\src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\user\CLionProjects\ollaborative-filtering-system

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	"D:\CLion 2025.1.2\bin\cmake\win\x64\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"D:\CLion 2025.1.2\bin\cmake\win\x64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\user\CLionProjects\ollaborative-filtering-system\CMakeFiles C:\Users\user\CLionProjects\ollaborative-filtering-system\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\user\CLionProjects\ollaborative-filtering-system\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RecommenderCore

# Build rule for target.
RecommenderCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 RecommenderCore
.PHONY : RecommenderCore

# fast build rule for target.
RecommenderCore/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/build
.PHONY : RecommenderCore/fast

#=============================================================================
# Target rules for targets named recsys

# Build rule for target.
recsys: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 recsys
.PHONY : recsys

# fast build rule for target.
recsys/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\recsys.dir\build.make CMakeFiles/recsys.dir/build
.PHONY : recsys/fast

# target to build an object file
DataHandler/CSVLoader.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/DataHandler/CSVLoader.obj
.PHONY : DataHandler/CSVLoader.obj

# target to preprocess a source file
DataHandler/CSVLoader.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/DataHandler/CSVLoader.i
.PHONY : DataHandler/CSVLoader.i

# target to generate assembly for a file
DataHandler/CSVLoader.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/DataHandler/CSVLoader.s
.PHONY : DataHandler/CSVLoader.s

# target to build an object file
Models/Item.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/Item.obj
.PHONY : Models/Item.obj

# target to preprocess a source file
Models/Item.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/Item.i
.PHONY : Models/Item.i

# target to generate assembly for a file
Models/Item.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/Item.s
.PHONY : Models/Item.s

# target to build an object file
Models/Rating.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/Rating.obj
.PHONY : Models/Rating.obj

# target to preprocess a source file
Models/Rating.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/Rating.i
.PHONY : Models/Rating.i

# target to generate assembly for a file
Models/Rating.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/Rating.s
.PHONY : Models/Rating.s

# target to build an object file
Models/User.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/User.obj
.PHONY : Models/User.obj

# target to preprocess a source file
Models/User.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/User.i
.PHONY : Models/User.i

# target to generate assembly for a file
Models/User.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RecommenderCore.dir\build.make CMakeFiles/RecommenderCore.dir/Models/User.s
.PHONY : Models/User.s

# target to build an object file
main.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\recsys.dir\build.make CMakeFiles/recsys.dir/main.obj
.PHONY : main.obj

# target to preprocess a source file
main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\recsys.dir\build.make CMakeFiles/recsys.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\recsys.dir\build.make CMakeFiles/recsys.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... RecommenderCore
	@echo ... recsys
	@echo ... DataHandler/CSVLoader.obj
	@echo ... DataHandler/CSVLoader.i
	@echo ... DataHandler/CSVLoader.s
	@echo ... Models/Item.obj
	@echo ... Models/Item.i
	@echo ... Models/Item.s
	@echo ... Models/Rating.obj
	@echo ... Models/Rating.i
	@echo ... Models/Rating.s
	@echo ... Models/User.obj
	@echo ... Models/User.i
	@echo ... Models/User.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

